version: 2.1
orbs:
  docker: circleci/docker@2.1.3

jobs:
  test-python:
    docker:  
      - image: python:3.10-slim
    steps:
      - checkout
      - run:
          name: Clear pip cache
          command: pip cache purge
      - run:
          name: Installer les dépendances
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/my-app:latest .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/my-app:latest

workflows:
  build-and-test:
    jobs:
      - test-python
      - build_docker_image
