version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:  # Ajout d'un environnement Docker
      - image: circleci/python:3.12  # Vous pouvez ajuster la version de Python si nécessaire
    steps:
      - checkout
      - run:
          name: Clear pip cache
          command: pip cache purge
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
        
workflows:
  build-and-test:
    jobs:
      - test-python


