version: 2.1
orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.3

jobs:
  test-python:
    docker:  
      - image: circleci/python:3.10.2
    steps:
      - checkout
      - run:
          name: Clear pip cache
          command: pip cache purge
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest
        
workflows:
  build-and-test:
    jobs:
      - test-python
