# Generated by Django 5.0.8 on 2024-09-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_initial'),
        ('oc_lettings_site', '0004_remove_lettings_adress_letting_profiles_user_and_mode'),
    ]

    operations = [
    ]
